
on:
  push:
    branches: [ main, dev, 'dev/*' ]
  pull_request:
    branches: [ main, dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r binder/requirements.txt
    - name: Build draft html
      run: |
        jupyter-book build ./content 
    - name: Deploy 
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: content/_build/html
    - name: Archive results
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: content/_build  
