on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r binder/requirements.txt
      - name: Build draft html
        run: |
          jupyter-book build ./content --builder singlehtml
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: singlehtml
          path: content/_build
